NetworkExpansion: 0
TimeDomainReductionFolder: "tdr_setup"
ModelingToGenerateAlternativeIterations: 3
ParameterScale: 0
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 0
CO2CapWiggle: 0.0
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
MethodofMorris: 0
Reserves: 0
StorageLosses: 0
OperationWrapping: 0
CO2CapPeriods: 1
OverwriteResults: 0
UCommit: 2
ModelingToGenerateAlternatives: 0
MinCapReq: 0
CO2Cap: 2
WriteShadowPrices: 0
